const data = {
  products: [
    {
      name: 'Allen Solly Slim shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Allen Solly',
      rating: 4.5,
      numReviews: 10,
      description: 'Stay effortlessly stylish with the Allen Solly Slim Shirt – a perfect blend of comfort, fit, and timeless fashion.',
    },
    {
      name: 'USPA Fit Shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 250,
      countInStock: 0,
      brand: 'USPA',
      rating: 4.0,
      numReviews: 10,
      description: 'Elevate your style with the USPA Fit Shirt—combining comfort and sophistication for a casually refined look. Dress sharp effortlessly!',
    },
    {
      name: 'Mufti Slim Pant',
      category: 'Pants',
      image: '/images/pant1.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Mufti',
      rating: 4.5,
      numReviews: 14,
      description: 'Elevate your style effortlessly with these sleek, tailored trousers. Comfort meets trend in every stitch.',
    },
    {
      name: 'Bennetton Denim Pant',
      category: 'Pants',
      image: '/images/pant3.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Bennetton',
      rating: 4.5,
      numReviews: 10,
      description: 'Feel the ultimate comfort and style in Bennetton Denim Pants – your go-to choice for casual chic vibes!',
    },
    {
      name: 'ASUS Zen Mobile',
      category: 'Mobile',
      image: '/images/mobile1.jpg',
      price: 65,
      countInStock: 5,
      brand: 'ASUS',
      rating: 4.5,
      numReviews: 10,
      description: 'Sleek design, powerful performance. Capture lifes moments with precision. Your everyday companion for seamless connectivity and style.',
    },
    {
      name: 'Apple XR Iphone',
      category: 'Mobile',
      image: '/images/iphone1.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'Meet the Apple XR iPhone – sleek design, stunning display, and powerful performance in one pocket-sized marvel. Elevate your experience!',
    },
    {
      name: 'Apple 7s Iphone',
      category: 'Mobile',
      image: '/images/iphone2.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'Meet the Apple 7s iPhone – sleek design, stunning camera, and powerful performance for a seamless, tech-savvy lifestyle.',
    },
    {
      name: 'Apple mac Book',
      category: 'Laptop',
      image: '/images/img3.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'Meet the sleek and powerful Apple MacBook – your creative companion with stunning design and lightning-fast performance. Elevate your experience!',
    },

    {
      name: 'Dell Laptop',
      category: 'Laptop',
      image: '/images/img4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Dell',
      rating: 4.5,
      numReviews: 10,
      description: 'Sleek design, blazing speed, and vibrant display for work or play. Elevate your tech game effortlessly!',
    },
  ],
};
export default data;
